added a way to clear all goals (so we can set just one goal for them at run time)... villagers are broken still though...
IndexOutOfRangeException: Index was outside the bounds of the array.
Swordfish.Navigation.Actor.TryGoalAtHelper (System.Int32 relativeX, System.Int32 relativeY, Swordfish.Navigation.PathfindingGoal goal, Swordfish.Navigation.Cell& current, Swordfish.Navigation.Cell& result, System.Int32& currentDistance, System.Int32& nearestDistance) (at Assets/Swordfish/Navigation/Actor.cs:91)
Swordfish.Navigation.Actor.FindNearestGoal (System.Boolean usePriority) (at Assets/Swordfish/Navigation/Actor.cs:122)
Swordfish.Navigation.Actor.GotoNearestGoal (System.Boolean usePriority) (at Assets/Swordfish/Navigation/Actor.cs:154)
Swordfish.Navigation.Actor.GotoNearestGoalWithPriority () (at Assets/Swordfish/Navigation/Actor.cs:150)
Villager.Tick () (at Assets/Scripts/RTSCore/Villager.cs:166)
Swordfish.Navigation.Actor.FixedUpdate () (at Assets/Swordfish/Navigation/Actor.cs:223)